# permissions for end users to view geoffreys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: geoffrey-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-helloworld-operator
    app.kubernetes.io/part-of: k8s-helloworld-operator
    app.kubernetes.io/managed-by: kustomize
  name: geoffrey-viewer-role
rules:
- apiGroups:
  - batch.geoffrey.dev
  resources:
  - geoffreys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.geoffrey.dev
  resources:
  - geoffreys/status
  verbs:
  - get
