---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.geoffrey.dev
  resources:
  - geoffreys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.geoffrey.dev
  resources:
  - geoffreys/finalizers
  verbs:
  - update
- apiGroups:
  - batch.geoffrey.dev
  resources:
  - geoffreys/status
  verbs:
  - get
  - patch
  - update
